#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

terminal="kitty"

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true 
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a "firefox" border_width=0


pkill -15 picom 2>/dev/null
picom & disown
#sleep 1
pkill -15 polybar 2>/dev/null
bash ~/.config/bspwm/polybar.sh
#sleep 1
pkill -15 feh
feh --bg-fill --no-fehbg ~/.config/bspwm/patata-kawai.jpg & disown
